# Generated by Django 3.2.7 on 2021-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_index', models.AutoField(primary_key=True, serialize=False)),
                ('chat_title', models.CharField(default=False, max_length=200)),
                ('chat_other_id', models.CharField(default=False, max_length=256)),
            ],
            options={
                'verbose_name': '채팅 목록',
                'db_table': 'chat',
            },
        ),
    ]
