# Generated by Django 3.2.7 on 2021-10-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_signup', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_index', models.AutoField(primary_key=True, serialize=False)),
                ('chat_title', models.CharField(default=False, max_length=200)),
                ('chat_other_id', models.CharField(default=False, max_length=256)),
            ],
            options={
                'verbose_name': '채팅 목록',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='User_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_chat_index', models.ForeignKey(db_column='uc_chat_index', default=False, on_delete=django.db.models.deletion.CASCADE, to='chatting.chat')),
                ('uc_user_id', models.ForeignKey(db_column='uc_user_id', default=False, on_delete=django.db.models.deletion.CASCADE, to='login_signup.user')),
            ],
            options={
                'verbose_name': '유저-채팅 테이블',
                'db_table': 'user_chat',
            },
        ),
    ]
