# Generated by Django 3.2.7 on 2021-09-27 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_rename_my_user_id_user_user_id'),
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc_chat_index', models.ForeignKey(db_column='uc_chat_index', default=False, on_delete=django.db.models.deletion.CASCADE, to='chatting.chat')),
                ('uc_user_id', models.ForeignKey(db_column='uc_user_id', default=False, on_delete=django.db.models.deletion.CASCADE, to='login_signup.user')),
            ],
            options={
                'verbose_name': '유저-채팅 테이블',
                'db_table': 'user_chat',
            },
        ),
    ]
