# Generated by Django 3.2.7 on 2021-10-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_signup', '0001_initial'),
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('msg_index', models.AutoField(primary_key=True, serialize=False)),
                ('msg_datetime', models.DateTimeField(auto_now_add=True)),
                ('msg_text', models.TextField()),
                ('msg_emo_name', models.CharField(default=False, max_length=256)),
                ('msg_chat_index', models.ForeignKey(db_column='msg_chat_index', default=False, on_delete=django.db.models.deletion.CASCADE, to='chatting.chat')),
                ('msg_user_id', models.ForeignKey(db_column='msg_user_id', default=False, on_delete=django.db.models.deletion.CASCADE, to='login_signup.user')),
            ],
            options={
                'verbose_name': '메세지 테이블',
                'db_table': 'msg',
            },
        ),
    ]
