# Generated by Django 3.2.7 on 2021-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_index', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default=False, max_length=64, unique=True)),
                ('user_pw', models.CharField(default=False, max_length=256)),
                ('user_name', models.CharField(default=False, max_length=400)),
            ],
            options={
                'verbose_name': '유저 테이블',
                'db_table': 'user',
            },
        ),
    ]
