# Generated by Django 3.2.7 on 2021-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_index',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
