# Generated by Django 3.2.7 on 2021-09-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_friend',
            name='uf_favorite',
            field=models.BooleanField(default='False'),
        ),
    ]
