# Generated by Django 3.2.7 on 2021-09-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_auto_20210922_1635'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_friend',
            name='uf_user_id',
            field=models.ForeignKey(db_column='uf_user_id', default=False, on_delete=django.db.models.deletion.CASCADE, to='login_signup.user'),
        ),
    ]
