# Generated by Django 3.2.7 on 2021-09-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_user_friend_uf_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_friend',
            options={},
        ),
        migrations.AlterModelTable(
            name='user_friend',
            table=None,
        ),
    ]
