# Generated by Django 3.2.7 on 2021-09-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20210922_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_friend',
            options={'verbose_name': '친구목록'},
        ),
        migrations.AlterModelTable(
            name='user_friend',
            table='user_friend',
        ),
    ]
