# Generated by Django 3.2.7 on 2021-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20210922_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_friend',
            name='uf_friend_id',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
