# Generated by Django 3.2.7 on 2021-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_index', models.IntegerField()),
            ],
            options={
                'verbose_name': '친구목록',
                'db_table': 'user_friend',
            },
        ),
    ]
