# Generated by Django 3.2.7 on 2021-09-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_friend',
            name='friend_index',
        ),
        migrations.AddField(
            model_name='user_friend',
            name='friend_id',
            field=models.CharField(default=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='user_friend',
            name='user_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='login_signup.user'),
        ),
    ]
